### ISSUE TITLE
Get React Icons Working with CRA and Next.js

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/monorepo#12]
Working with direct import. Having troubles with the packaging.

Vite seems to be working with: https://www.npmjs.com/package/vite-plugin-svgr

**Comment by 0xRowdy** [comment]
Move all the assets to our app instead of using react icons lib.

- [ ] Download the icons used in the UI
- [ ] Update imports to use dl'd assets
- [ ] Smoke test other apps
