### ISSUE TITLE
UI Member Card Updates

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/monorepo#152]
# Description

- Currently, we have a MemberCard that is a dropdown. MemberCard should not be a Dropdown. There should be a MemberCard (or MemberAvatar), which fetches for a memberProfile and displays it, and there should be a MemberCardDropdown which has the full dropdown. 

- MemberCard has extra padding. The padding should be applied from outside the library. 

- Make these adjustments to thte UI library and the admin app.

**Comment by 0xRowdy** [comment]
We're adding a useMemberProfile hook that will replace the MemberCard/MemberAvatar component described above.
