### ISSUE TITLE
Enable Changing Color Theme in UI Package

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/monorepo#169]
Full color audit (make sure that editing with custom colors updates all colors, including moloch pack UI)

@jordanlesich to add details

**Comment by 0xRowdy** [comment]
Have we tried this via the theme provider? I was talking to Dekan about changing the colors of the vite stater we're using for the protocol guild.

**Comment by santteegt** [comment]
**Tasks done**: Enable UI theme color customization
**Time spent**: 0.5 hours
