### ISSUE TITLE
Get correct ENS name in profile fetch

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/monorepo#186]
# details

the ens fetch is likely just grabbing a list of all ens names associated to the account address and return the 1st one in here:

https://github.com/HausDAO/monorepo/blob/develop/libs/profile-data/src/profile.ts#L29

we need to figure out a better query to get the one set as the resolver for the address - change this query:

https://github.com/HausDAO/monorepo/blob/develop/libs/profile-data/src/subgraph/queries-ens/account.graphql

this is the subgraph:

https://thegraph.com/hosted-service/subgraph/ensdomains/ens

**Comment by santteegt** [comment]
Using https://app.ens.domains/address/0x15c6ac4cf1b5e49c44332fb0a1043ccab19db80a/registrant we can see an example of an address having a primary ENS name (or reverse record). In this case, we cannot easily identify that ENS name by just querying the ENS subgraph by account. A library capable of doing reverse resolution can be used in this case

**Comment by santteegt** [comment]
**Tasks done**: explore subgraph queries that allow us to identify the main ENS record from an address. Ended up implementing reverse resolution using etherjs
**Time spent**: 3 hours

**Comment by spengrah** [comment]
I'm now seeing the correct ENS in my wallet connection and on my profile, but it still shows up as an old/incorrect ENS name in the delegate view

![image](https://user-images.githubusercontent.com/13247381/220485080-7f170f90-83fe-4cdc-bdf1-bda5a977ed67.png)

**Comment by skuhlmann** [comment]
> I'm now seeing the correct ENS in my wallet connection and on my profile, but it still shows up as an old/incorrect ENS name in the delegate view on `join.daohaus.fun` and also in `signal.daohaus.fun`
> 
> ![image](https://user-images.githubusercontent.com/13247381/220485080-7f170f90-83fe-4cdc-bdf1-bda5a977ed67.png)

This screenshot is not for an app maintained in this repo. Going to keep this closed as it is fixed in the tooling.
