### ISSUE TITLE
Add error to formbuilder when not inside txbuidler context

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/monorepo#197]
FormBuilder should throw an error when submitting without the TXBuilderContext set up somewhere in the app. Somehow it just hangs there. My dumb ass spends 20 mins trying to troubleshoot every time.

**Comment by santteegt** [comment]
**Tasks done**: implement an erorr status in FormBuilder for cases when TxBuilder context is missing
**Time spent**: 1 hour
