### ISSUE TITLE
MacroPack: Create Proposal Action Data Component

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/monorepo#208]
### Proposal action data

![](https://i.imgur.com/3VRM1xg.png)

**Comment by santteegt** [comment]
**Tasks done**: Implement macro component & test on external app
**Time spent**: 2 hours

**Comment by santteegt** [comment]
Also included a ProposalDetails macro within the same PR.

**Time spent**: 1 hour

![Image](https://user-images.githubusercontent.com/926341/221442995-2a2c2064-fb42-4eb2-94c4-43b7c7a59dd5.png)
