### ISSUE TITLE
MacroPack: Create Member List

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/monorepo#209]
### Members list
- can we configure the columns
    - types hell
- or do we need to hard code for now
- upgrade to tan table?
- delegate modal can come over
- pass in action panel - where you can send a link to a form in your app

![](https://i.imgur.com/nNweb7h.png)

**Comment by santteegt** [comment]
**Tasks done**

#### Macros

* DaohausTable
* MemberList
  * MembersOverview

**Time spent**: 2.5 hours
