### ISSUE TITLE
Moloch Pack: Create a Member Profile Macro

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/monorepo#239]
Profile page stuff:

https://admin.daohaus.club/#/molochv3/0x5/0xc035dd7cda32ae73f0f306ed56658527aad47648/members/0x83ab8e31df35aa3281d630529c6f4bf5ac7f7abf

**Comment by santteegt** [comment]
**Tasks done**
#### Macros

* MemberProfileCard
  * MemberProfileAvatar
  * MemberProfileMenu
  * MemberProfile
  * MemberTokens
  * ManageDelegate   

#### TODOs:

* ManageDelegate
  * How to import `MANAGE_DELEGATE` form lego
  * import Custom Field legos from the new moloch package

**Time spent**: 3 hours
