### ISSUE TITLE
Versioning roadmap

### ISSUE THREAD

**Issue by jordanlesich** [HausDAO/monorepo#27]
Basic Functionality
- Start by getting CI/CD running jscutlery/semver
- Manually setting versions from develop to master
- Test dependencies to ensure that they all update
- Test external apps to make sure they are using the latest version

Basic Enforcement
- Basic husky commit formats
- On commit husky format guard 
- Discover whether we should be doing this in develop or master (based on husky's recommendations) 
- Test that husky is updating specified deps
- Test that husky and NX are bumping all affected libraries
- Test external apps

Ongoing Monorepo Hygiene
- Pre push hook lint and build checks 
- Integrate with husky current versioning 
- Ideate on some other enforcement mechanisms, especially if we start to write tests. 
- Test all.

**Comment by earth2travis** [comment]
Need a doc on how we manually do this prior to us getting it automated
