### ISSUE TITLE
Add preview packages 

### ISSUE THREAD

**Issue by pi0neerpat** [HausDAO/monorepo#272]
### App

- [ ] [Admin](https://admin.daohaus.fun)
- [ ] [Summon](https://summon.daohaus.fun)
- [ ] [Hub](https://hub.daohaus.fun)
- [X] [Toolbox](https://toolbox.daohaus.fun/)

### Feature Type

- [X] New Feature
- [ ] Enhancement

### Feature

Offering to implement auto-publishing PR packages, using a Github Action I  built https://github.com/UseKeyp/publish-pr-packages

![image](https://user-images.githubusercontent.com/35622595/222980792-50aba2c4-0a9d-4ed9-9270-1ab919ef8788.png)

**Comment by dekanbro** [comment]
@pi0neerpat How does this work?

**Comment by pi0neerpat** [comment]
When a PR is opened, the package is built and published automatically. This allows you to test locally, without having to use yarn-link
