### ISSUE TITLE
UI Bug: Proposal status if voting power has changed

### ISSUE THREAD

**Issue by shayanb** [HausDAO/monorepo#281]
### Feature

UI Proposal status

### App

- [X] [Admin](https://admin.daohaus.fun)
- [X] [Summon](https://summon.daohaus.fun)
- [ ] [Hub](https://hub.daohaus.fun)
- [ ] [Toolbox](https://toolbox.daohaus.fun/)

### Expected Behavior

Setup:
- A DAO with 2 members 10 voting tokens each
- A proposal is submitted and sponsored by 1 --> 50% votes
- Given that quorum is 20%, the proposal should pass
- 10 more members with 10 voting tokens are added to the DAO

Based on `quorumPercent` (in BAAL) at the time of the proposal, the proposal should pass with 50% voting power, but the UI shows that the proposal will fail. The behaviour on-chain is that it [passed](https://etherscan.io/tx/0x6af4d645a8dd71048e9dedc8e8a85960aa2f4b23cd119737adcf899586ca561d). 

### Actual Behavior

the UI shows that the proposal will fail. The behaviour on-chain is that it [passed](https://etherscan.io/tx/0x6af4d645a8dd71048e9dedc8e8a85960aa2f4b23cd119737adcf899586ca561d). 

### Screenshots and Context

<img width="1220" alt="Screenshot 2023-03-26 at 11 27 42 PM" src="https://user-images.githubusercontent.com/309108/227835826-5f0ef42b-54ef-430e-8cf0-4b280f2d168b.png">

After executing the proposal: 
<img width="1166" alt="Screenshot 2023-03-26 at 11 29 43 PM" src="https://user-images.githubusercontent.com/309108/227835854-e8832d37-4699-4579-a055-30440b42b94e.png">

**Comment by skuhlmann** [comment]
FYI - We've started this one. 

https://github.com/HausDAO/monorepo/tree/fix/292-quorum-snapshot

It requires a subgraph change before we can proceed. Will be looking for a time when gas is low to get these published at a price we can stomach.
