### ISSUE TITLE
Arbitrum Proposal Details not loading

### ISSUE THREAD

**Issue by dekanbro** [HausDAO/monorepo#329]
### Feature

Proposal Details

### App

- [X] [Admin](https://admin.daohaus.fun)
- [ ] [Summon](https://summon.daohaus.fun)
- [ ] [Hub](https://hub.daohaus.fun)
- [ ] [Toolbox](https://toolbox.daohaus.fun/)

### Expected Behavior

When using the transfer erc20 proposal type the resulting proposal details should show the decoded multicall parameters.

### Actual Behavior

Currently the decoded details are empty and an error is thrown in the console

### Steps to Reproduce

Go to http://127.0.0.1:4200/#/molochV3/0xa4b1/0xdd4ad001cd16be4ca648d6a111dd3f4d45c4243e/proposals/17

### Screenshots and Context

It appears the arbitrum scan api call is not returning the correct abi.

this is the url

https://api.arbiscan.io/api?module=contract&action=getabi&address=0xff970a61a04b1ca14834a43f5de4533ebddb5cc8&apiKey=...

this contract is USDC on arbitrum and it is an transparent upgradable proxy. So the issue may be that it is not getting the implementation. Because this is a standard erc20 transfer proposal can we use a local abi?

**Comment by Data-Nexus** [comment]
It seems like this should do a check to see if the contract is a proxy and instead fetch the ABI's for the implemented contract. In this case `0x1efb3f88bc88f03fd1804a5c53b7141bbef5ded8`
