### ISSUE TITLE
Upgrade daohaus-connect to use newer web3modal, wagmi, view and move to wallect connect v2

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/monorepo#339]
### App

- [X] [Admin](https://admin.daohaus.fun)
- [X] [Summon](https://summon.daohaus.fun)
- [X] [Hub](https://hub.daohaus.fun)
- [X] [Toolbox](https://toolbox.daohaus.fun/)

### Feature Type

- [X] New Feature
- [X] Enhancement

### Feature

Details in this thread:
https://discord.com/channels/709210493549674598/1124048907958231172

1. Upgrade web3modal in daohaus connect - COMPLETE
2. Update the main tx handlers in txbuilder from ethers to viem - with the viem publicClient from web3modal - IN PROGRESS
3. Update wallect connect to v2 and ensure the wallect connect proposal works
4. Test and ensure the app works when loaded as a safe app (we might need to deploy to daohaus.fun to test this)

### ethers.js to viem checklist

- [x] tx-builder abi
createContract and read contract

- [x] tribute inputs
- balanceOf calls

- [x] readyForProcessing.tsx
- create contract

- [x] useErc20.tsx
- create contract

- [x] proposalDetailsHelper.tsx
- create contract

- [x] decoding.tsx
- create contract

- [x]  tx-builder multicall
- upgraded the one in tx-builder
- keeping ethers in contract-utils as that lib still relies on ethers

- [x]  formatting.ts
utils format ether
https://viem.sh/docs/ethers-migration.html#formatether

- [x] utils/general
formatting
https://viem.sh/docs/ethers-migration.html#formatether

- [x]  utils/typeguard.ts
isaddress utils
https://viem.sh/docs/ethers-migration.html#isaddress

- [x]  more to clean up in txBuilderUtils
some types and some helpers/big number ect...

- [x] encoding.ts and getCode in abi.ts

### upgrade considerations

- [ ] BigNumber to BigInt - requires tsconfig target: ES2020 or greater (esnext) -- this seems to be if you want to represent bigints using the `n` syntax -- `100n` = 100 as a bigint, otherwise `BigInt(100)` seems to work
- [ ] viem for typechain -- typechain no longer required? (https://github.com/dethcrypto/TypeChain/issues/844) - maybe no need anymore for `@daohaus/baal-contracts` - instead pass stringified abi to parseabi -- https://viem.sh/docs/abi/parseAbi.html so maybe just need to migrate helpers into abi lib

### [Test Scenarios](https://hackmd.io/Ls_fn_8YShWqB7OdGBFTlA?view)

**Comment by earth2travis** [comment]
Laid out a fe ideas for [Test Scenarios](https://hackmd.io/Ls_fn_8YShWqB7OdGBFTlA?view)

**Comment by skuhlmann** [comment]
TODO test:
- Erc20 field that check token allowance. ensure the greater than > 0 check is working

**Comment by skuhlmann** [comment]
TODO: Test multi action estimate on proposals

**Comment by skuhlmann** [comment]
how can we not have this happen?
![Screenshot from 2023-07-19 14-52-10](https://github.com/HausDAO/monorepo/assets/6923345/f80a7f38-37b9-46c5-9e51-27b0b2a202c4)

**Comment by skuhlmann** [comment]
update the gasFee function to use something like this:

https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/actions/network-status/fetchFeeData.ts

ours using ethers is here libs/utils/crs/ethersFallback.ts
`getGasCostEstimate`

**Comment by skuhlmann** [comment]
done - more or less.
