### ISSUE TITLE
viem walletClient.writeContract returning wrong transaction hash

### ISSUE THREAD

**Issue by dekanbro** [HausDAO/monorepo#415]
### Feature

transaction builder

### App

- [X] [Admin](https://admin.daohaus.club)
- [ ] [Summon](https://summon.daohaus.club)
- [ ] [Hub](https://hub.daohaus.club)
- [ ] [Toolbox](https://toolbox.daohaus.club/)

### Expected Behavior

When making a proposal the transaction hash is used to update and refetch the graph. Once the indexor is updated it returns the user to the proposal page to view the new Proposal for voting.

### Actual Behavior

Proposal returns a TransactionNotFoundError in a toast and shows that their was a failure. the proposal actually is created correctly but the messaging to the user is confusing.

When using prepareTX in libs/tx-builder/src/utils/txBuilderUtils.ts it seems that

https://github.com/HausDAO/monorepo/blob/develop/libs/tx-builder/src/utils/txBuilderUtils.ts#L223

is returning the wrong transaction hash.

this seems to happen periodically with all transactions and every time when using wallet connect and Safe

### Steps to Reproduce

1. Connect with Wallet Connect to Safe
2. make a proposal
3. execute from Safe
4. return to app

**Comment by skuhlmann** [comment]
**Workaround implemented here:**
https://github.com/HausDAO/monorepo/pull/414

It would be ideal to remove this code if/when viem handles the issue
