### ISSUE TITLE
Details Description text styling 

### ISSUE THREAD

**Issue by dekanbro** [HausDAO/monorepo#439]
### Feature

Proposal Details Markdown text

### App

- [X] [Admin](https://admin.daohaus.club)
- [ ] [Summon](https://summon.daohaus.club)
- [ ] [Hub](https://hub.daohaus.club)
- [X] [Toolbox](https://toolbox.daohaus.club/)

### Expected Behavior

After the update to support markdown the text in desciptions is too small and does not match up with the other text in the theme. I think this may require some custom styles to get the html generated from markdown in line with the theme.

### Actual Behavior

text is small and hard to read and inherits the default p tag styles

### Steps to Reproduce

example proposal: https://admin.daohaus.fun/#/molochV3/0xa/0xf5d6b637a9185707f52d40d452956ca49018247a/proposal/41

### Screenshots and Context

![](https://hackmd.io/_uploads/HkHqPJvMp.png)

**Comment by dekanbro** [comment]
this is using react markdown. potentially could use the className param to add a wrapper that could be styled

https://github.com/remarkjs/react-markdown#fields-1

**Comment by dekanbro** [comment]
code in reference https://github.com/HausDAO/monorepo/blob/develop/libs/moloch-v3-macro-ui/src/components/ProposalDetails/ProposalDetails.tsx#L64

**Comment by memosys** [comment]
@dekanbro want to take this one as well!

**Comment by dekanbro** [comment]
i added a fix on this. #454
