### ISSUE TITLE
Responsiveness of Markdown editor dialog

### ISSUE THREAD

**Issue by dekanbro** [HausDAO/monorepo#440]
### Feature

Markdown Field

### App

- [ ] [Admin](https://admin.daohaus.club)
- [ ] [Summon](https://summon.daohaus.club)
- [ ] [Hub](https://hub.daohaus.club)
- [X] [Toolbox](https://toolbox.daohaus.club/)

### Expected Behavior

The dialog that pops up for a larger view of the editor should be more responsive to different screen sizes.

### Actual Behavior

size of dialog seems inconsistent when switching from edit to preview and is not responsive

### Screenshots and Context

![image](https://github.com/HausDAO/monorepo/assets/8740799/14c577cb-2f1a-42ec-906f-8f85d0e90724)

https://github.com/HausDAO/monorepo/blob/develop/libs/moloch-v3-fields/src/fields/MarkdownField.tsx#L105

**Comment by memosys** [comment]
@dekanbro I want to take this one up!

**Comment by dekanbro** [comment]
fixed with #443
