### ISSUE TITLE
Numbers Overflow Button on Network Token Form

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/monorepo#444]
### Feature

TRANSFER_NETWORK_TOKEN_SIDECAR Proposal Form

### App

- [X] [Admin](https://admin.daohaus.club)
- [ ] [Summon](https://summon.daohaus.club)
- [ ] [Hub](https://hub.daohaus.club)
- [ ] [Toolbox](https://toolbox.daohaus.club/)

### Expected Behavior

Decimals will be truncated or button would expand to fit all digits

### Actual Behavior

Digits break out of button

### Steps to Reproduce

1. Go to [Safes](https://admin.daohaus.club/#/molochv3/0x64/0xe2f816d08c568a447d3804b265f1e277bc2c688d/safes) view on Gnosis Chain
2. Scroll down to Stash safe, click `...` > Transfer xDAI
3. Scroll down to "Request XDAI on Gnosis Chain" on the [Network Token Transfer](https://admin.daohaus.club/#/molochv3/0x64/0xe2f816d08c568a447d3804b265f1e277bc2c688d/new-proposal?formLego=TRANSFER_NETWORK_TOKEN_SIDECAR&defaultValues={%22safeAddress%22:%220xa68ca8c9165b09be9293ddfc23b3be86a2f346a0%22}) proposal form

### Browser

Brave

### Screenshots and Context

<img width="660" alt="image" src="https://github.com/HausDAO/monorepo/assets/522182/6c023d42-a937-4bea-991c-08139deaf98f">

I believe a solution has already been implemented on the `TRANSFER_ERC20_SIDECAR` proposal form and can be duplicated here.

**Comment by khoadangtran** [comment]
Hey, I want to work on this issue, Can you please assign it to me?
