### ISSUE TITLE
Fix Proposal Description Styling

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/monorepo#445]
### Feature

Proposals

### App

- [X] [Admin](https://admin.daohaus.club)
- [ ] [Summon](https://summon.daohaus.club)
- [ ] [Hub](https://hub.daohaus.club)
- [ ] [Toolbox](https://toolbox.daohaus.club/)

### Expected Behavior

Font size and link color should be consistent with rest of page as defined in [DAOhaus v3 Pattern Library](https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library?type=design&node-id=1%3A25&mode=design&t=JusYgSTsW0Xo0GGU-1)

### Actual Behavior

Text is displayed extremely small and there is not enough contrast to see the links

### Steps to Reproduce

1. Create new proposal
2. Add link using Markdown editor
3. Submit proposal
4. View proposal 

### Browser

Brave

### Screenshots and Context

<img width="683" alt="image" src="https://github.com/HausDAO/monorepo/assets/522182/5cf77776-820b-402c-ad80-efd10c5c5958">

This bug was introduced when the Markdown editor was added to proposals

**Comment by khoadangtran** [comment]
Hey, I want to work on this issue, Can you please assign it to me?

**Comment by earth2travis** [comment]
@khoadangtran good luck. If you have any questions please do not hesitate to come through on Discord: https://discord.gg/tN9TaqDT

**Comment by dekanbro** [comment]
I think this could be resolved by making font size 1.5 rem in the description content
