### ISSUE TITLE
Conversion to BigInt error on proposal details

### ISSUE THREAD

**Issue by dekanbro** [HausDAO/monorepo#446]
### Feature

Proposal Details Helpers

### App

- [X] [Admin](https://admin.daohaus.club)
- [ ] [Summon](https://summon.daohaus.club)
- [ ] [Hub](https://hub.daohaus.club)
- [ ] [Toolbox](https://toolbox.daohaus.club/)

### Expected Behavior

It should show a summary of minted gov units

### Actual Behavior

https://admin.daohaus.fun/#/molochV3/0x5/0x4f550a8ae11e284687ced8cf07c12a05800fc854/proposal/27

### Screenshots and Context

![image](https://github.com/HausDAO/monorepo/assets/8740799/b8bf0bc3-79ba-4513-ab27-fafcd8f9fa10)

**Comment by skuhlmann** [comment]
Cannot reproduce with this old goerli dao. Stale and closing.
