### ISSUE TITLE
Long text breaks out of card - visual bug

### ISSUE THREAD

**Issue by dekanbro** [HausDAO/monorepo#451]
### Feature

Proposal list item 

### App

- [X] [Admin](https://admin.daohaus.club)
- [ ] [Summon](https://summon.daohaus.club)
- [ ] [Hub](https://hub.daohaus.club)
- [ ] [Toolbox](https://toolbox.daohaus.club/)

### Expected Behavior

text should be hyphened, truncated or some other solution so it doesn't break the card

### Actual Behavior

Long text breaks out of card 

### Screenshots and Context

![image](https://github.com/HausDAO/monorepo/assets/8740799/c3ea4e65-6f6d-4524-9848-7ec0d7e00276)

another example 
![image](https://github.com/HausDAO/monorepo/assets/8740799/fdb8e4b8-19a4-48bc-9b6c-c5cd8002c851)

**Comment by dekanbro** [comment]
@memosys

**Comment by vani11aa** [comment]
Fixed in PR #493
