### ISSUE TITLE
Multiple pages of the admin.daohaus.club no longer work for Goerli DAOs

### ISSUE THREAD

**Issue by j-h-scheufen** [HausDAO/monorepo#477]
### Feature

page rendering

### App

- [X] [Admin](https://admin.daohaus.club)
- [ ] [Summon](https://summon.daohaus.club)
- [ ] [Hub](https://hub.daohaus.club)
- [ ] [Toolbox](https://toolbox.daohaus.club/)

### Expected Behavior

The pages should render

### Actual Behavior

Pages are white. Seemingly content is missing in the html output.

### Steps to Reproduce

1. Go to a DAO's admin pages that is deployed on Goerli, e.g. https://admin.daohaus.club/#/molochv3/0x5/0xd93686fd072e97963460fec1baf7c0e47e00b9fe/safes.
2. The page is empty / white.

### Browser

Chrome

### Screenshots and Context

When reporting this issue in Discord, the suspicion was that it could be related to Gnosis Safe turning off Goerli support.

Other page where the problem was observed: `/new-proposal?formLego=TRANSFER_NETWORK_TOKEN`

DOM tree for white page:
![image](https://github.com/HausDAO/monorepo/assets/1975494/b8ad84ee-d9cb-413d-bfa6-247d05f50419)

**Comment by scottrepreneur** [comment]
Goerli is deprecated as of the recent Dencun fork in January. Do you need help migrating your DAO to Sepolia?

**Comment by j-h-scheufen** [comment]
Hi Scott, I just made this ticket based on this discussion with @dekanbro in Discord: https://discord.com/channels/709210493549674598/1082758136093478932/1209509349848776736

I am migrating to Sepolia now. But maybe a warning would be appropriate on the pages as I think you can still summon DAOs on Goerli, but then it becomes a trap as you can't use the Daohaus UI fully.

**Comment by scottrepreneur** [comment]
> I think you can still summon DAOs on Goerli, but then it becomes a trap as you can't use the Daohaus UI fully.

Yeah fair. Higher priority issue is preventing summoning there probably! 🙏

**Comment by skuhlmann** [comment]
Goerli has been deprecated and removed from the admin app and tooling.
