### ISSUE TITLE
Token swap proposal uses keyword ‘release escrow’

### ISSUE THREAD

**Issue by wtfsayo** [HausDAO/monorepo#492]
### App

- [X] [Admin](https://admin.daohaus.club)
- [ ] [Summon](https://summon.daohaus.club)
- [ ] [Hub](https://hub.daohaus.club)
- [ ] [Toolbox](https://toolbox.daohaus.club/)

### Feature Type

- [ ] New Feature
- [X] Enhancement

### Feature

Not sure if it’s as intended but was confusing to me
<img width="617" alt="Screenshot_2024-04-10_at_11 36 08" src="https://github.com/HausDAO/monorepo/assets/82053242/79843ec3-5cf2-4f01-b358-2c6bc4888e8a">

**Comment by skuhlmann** [comment]
This is the name of the function - this component should probably keep the function names to provide full transparency. 

The area above could potentially have some more user friendly content to explain the action for this specific proposal type.

**Comment by skuhlmann** [comment]
Closing.
