### ISSUE TITLE
Add "Transfer Shares" proposal

### ISSUE THREAD

**Issue by scottrepreneur** [HausDAO/monorepo#525]
### App

- [X] [Admin](https://admin.daohaus.club)
- [ ] [Summon](https://summon.daohaus.club)
- [ ] [Contracts](https://docs.daohaus.club/contracts)
- [ ] [Contracts](https://docs.daohaus.club/subgraphs)
- [ ] [SDK](https://docs.daohaus.club/)

### Feature Type

- [ ] New Feature
- [X] Enhancement

### Feature

A proposal type that handles DAO share (burn/mint) transfer. 

- Default transfer ALL my shares
- Ask for recipient's address only
- Stretch: Toggle between transferring shares or loot

Calls:
- `burnShares(current address, max current shares)`
- `mintShares(recipient address, max current shares)`

**Comment by santteegt** [comment]
Here's some WIP:

* Add `transfer` option in dropdown menu for the current connected member

<img width="1084" alt="Screenshot 2024-10-15 at 12 03 05 AM" src="https://github.com/user-attachments/assets/066bd51d-ff5f-495d-94e6-c427d00ef073">

* Same under Member profile

<img width="933" alt="Screenshot 2024-10-15 at 12 02 39 AM" src="https://github.com/user-attachments/assets/823f7422-78df-4fb9-b530-515e317e6742">

* Modal with form to submit a `transfer` tokens tx. Works for shares/loot. Validates token is transferrable. Set Max Amount button with validation

<img width="674" alt="Screenshot 2024-10-15 at 12 02 18 AM" src="https://github.com/user-attachments/assets/b47cbd3f-9ce8-4e1f-887d-ed16e7d9e2ea">
